name = "XSLT"
uuid = "b76b70d0-c2e6-4f10-aa24-8ebd5c87d188"
authors = ["Rémi Vezy <VEZY@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
XSLT_jll = "aed1982a-8fda-507f-9586-7b0439959a61"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
